# Generated by Django 6.0.4 on 2026-05-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('skills', '0006_skill_image_delete_skillimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
    ]
