# Generated by Django 6.0.4 on 2026-05-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=20),
        ),
    ]
